workflows:
    react-native-android:
        name: Expo React native android
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic5"
        scripts:
          - name: Install npm dependencies
            script: | 
              npm install
          - name: Set Android SDK location
            script: | 
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          - name: Build Android release
            script: | 
              cd android
              ./gradlew bundleRelease
        artifacts:
            - android/app/build/outputs/**/*.aab
        publishing:
          email:
            recipients:
              - david@nevercode.io
            notify:
              success: true
              failure: false